project:
  type: website
  output-dir: "docs"
  title: "Title of this web report."
format:
  html:
    theme: www/web_report.scss
website:
  favicon: www/images/CPAL_favicon.ico
  description: Description of this web report.
#  site-url:
#  repo-url:
#  google-analytics:
#  cookie consent: implied
  navbar:
      logo: www/images/CPAL_Logo_White.png
      logo-href: "https://childpovertyactionlab.org/"
      search: FALSE
      collapse: TRUE
      right:
        - icon: house-door-fill
          text: "Home"
          href: web_report.html
        - icon: github
          text: "Github"
          href: "https://github.com/childpovertyactionlab/"
  page-footer:
    center: Copyright 2023 <b>[The Child Poverty Action Lab](https://childpovertyactionlab.org/).</b>
    background: "#008097"
