/* style.css — base CPAL styling */
/* Generated by cpaltemplates */

:root {
  /* CPAL Brand Colors */
  --cpal-midnight: #004855;
  --cpal-deep-teal: #006878;
  --cpal-coral: #E86A50;
  --cpal-sage: #5A8A6F;
  --cpal-slate: #5C6B73;
  --cpal-warm-gray: #9BA8AB;
  --cpal-gold: #D4A84B;
}

body {
  font-family: "Poppins", "Inter", sans-serif;
  background-color: #f8f9fa;
  color: #343a40;
}

/* Customize Shiny inputs */
.shiny-input-container {
  margin-bottom: 1em;
}

/* Buttons */
.btn {
  background-color: var(--cpal-deep-teal);
  color: #ffffff;
  border-radius: 4px;
}
.btn:hover {
  background-color: var(--cpal-midnight);
}

/* ============================================
   Reactable Table Styles (CPAL Branding)
   ============================================ */

/* Base reactable container */
.reactable-cpal {
  font-family: inherit;
}

/* Table header title and subtitle */
.cpal-table-header {
  margin-bottom: 1rem;
}

.cpal-table-title {
  font-size: 1.25rem;
  font-weight: 600;
  margin: 0 0 0.25rem 0;
  color: var(--cpal-midnight);
}

.cpal-table-subtitle {
  font-size: 0.9rem;
  color: #6c757d;
  margin: 0;
}

/* Table footer/source */
.cpal-table-footer {
  font-size: 0.8rem;
  color: #6c757d;
  font-style: italic;
  text-align: right;
  padding-top: 0.75rem;
  margin-top: 0.5rem;
  border-top: 1px solid #dee2e6;
}

/* Row hover enhancement */
.reactable-cpal .rt-tr:hover {
  background-color: rgba(0, 104, 120, 0.08);
}

/* Ensure table doesn't have double borders */
.reactable-cpal .rt-table {
  border-top: none;
}

/* Sort indicator styling */
.reactable-cpal .rt-sort-header:hover {
  background-color: rgba(0, 104, 120, 0.05);
}

/* Page size select styling */
.reactable-cpal .rt-page-size-select {
  border: 1px solid var(--cpal-deep-teal);
  border-radius: 4px;
  padding: 4px 8px;
}

/* ============================================
   Dark Mode Support
   ============================================ */

[data-bs-theme="dark"] .cpal-table-title {
  color: #e5e7eb;
}

[data-bs-theme="dark"] .cpal-table-subtitle,
[data-bs-theme="dark"] .cpal-table-footer {
  color: #9ca3af;
}

[data-bs-theme="dark"] .cpal-table-footer {
  border-top-color: #374151;
}

[data-bs-theme="dark"] .reactable-cpal {
  background-color: #1f2937;
  color: #e5e7eb;
}

[data-bs-theme="dark"] .reactable-cpal .rt-tr {
  color: #e5e7eb;
}

[data-bs-theme="dark"] .reactable-cpal .rt-tr:hover {
  background-color: rgba(0, 104, 120, 0.15);
}

[data-bs-theme="dark"] .reactable-cpal .rt-td {
  border-top-color: #374151;
}

[data-bs-theme="dark"] .reactable-cpal .rt-th {
  border-color: var(--cpal-deep-teal);
}

[data-bs-theme="dark"] .reactable-cpal .rt-search,
[data-bs-theme="dark"] .reactable-cpal .rt-page-size-select {
  background-color: #374151;
  border-color: var(--cpal-deep-teal);
  color: #e5e7eb;
}

[data-bs-theme="dark"] .reactable-cpal .rt-pagination {
  border-top-color: #374151;
  color: #e5e7eb;
}

[data-bs-theme="dark"] .reactable-cpal .rt-page-button {
  color: #e5e7eb;
}

[data-bs-theme="dark"] .reactable-cpal .rt-page-button:hover {
  background-color: #374151;
}
